from __future__ import annotations

import io

import pandas as pd
import xarray as xr

from open_csi_publisher.core.export import render_csv_with_metadata_header


def _ds(**attrs) -> xr.Dataset:
    ds = xr.Dataset(
        {"air_temperature": ("time", [1.0, 2.0, 3.0])},
        coords={"time": pd.date_range("2026-01-01", periods=3, freq="10min")},
    )
    ds.attrs.update(attrs)
    return ds


def test_csv_starts_with_hash_commented_metadata_lines():
    ds = _ds(title="Test Station", institution="UNIS")
    text = render_csv_with_metadata_header(ds)
    lines = text.splitlines()
    assert lines[0].startswith("#")
    assert any(line == "# title: Test Station" for line in lines)
    assert any(line == "# institution: UNIS" for line in lines)


def test_csv_data_rows_still_parse_correctly_after_the_header():
    ds = _ds(title="Test Station")
    text = render_csv_with_metadata_header(ds)
    df = pd.read_csv(io.StringIO(text), comment="#")
    assert list(df["air_temperature"]) == [1.0, 2.0, 3.0]
    assert "time" in df.columns


def test_csv_header_includes_provenance_fields_when_present():
    ds = _ds(
        title="Test Station",
        processing_software_version="0.1.0",
        config_hash="abc123",
        history="2026-01-01: generated by open_csi_publisher 0.1.0",
    )
    text = render_csv_with_metadata_header(ds)
    assert "# processing_software_version: 0.1.0" in text
    assert "# config_hash: abc123" in text
    assert "# history: 2026-01-01: generated by open_csi_publisher 0.1.0" in text


def test_csv_header_multiline_attr_value_does_not_break_comment_convention():
    ds = _ds(title="Test\nStation")  # pathological but shouldn't corrupt the file
    text = render_csv_with_metadata_header(ds)
    for line in text.splitlines():
        if line.strip() == "":
            continue
        assert line.startswith("#") or "," in line or line == "time,air_temperature"


def test_csv_with_no_attrs_still_produces_valid_csv():
    ds = _ds()
    text = render_csv_with_metadata_header(ds)
    df = pd.read_csv(io.StringIO(text), comment="#")
    assert len(df) == 3
